services:
  blackjack_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mpunsola/blackjack_api:latest
    environment:
      SPRING_DATASOURCE_URL: r2dbc:mysql://mysql:3306/blackjack_players
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "PegasusSplit*14"
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/blackjack_games
    ports:
      - '8080:8080'
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - app-network

  mongodb:
    image: 'mongo:6.0'
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: blackjack_games
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "secret123"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: 'mysql:8.0'
    container_name: mysql
    environment:
      MYSQL_DATABASE: blackjack_players
      MYSQL_ROOT_PASSWORD: "verysecret"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pverysecret" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  mysql_data:
